---
Sts.Region: us-west-2
Sts.Role: arn:aws:iam::610547539895:role/admin

Stack.Name: elasticsearch-resources-{{ env }}
Stack.Description: Containerized elasticsearch resources
Stack.Template: templates/stack.yml.j2
Stack.Tags:
  org:business:owner: Casecommons
  org:business:product: React Slingshot
  org:business:severity: High
  org:tech:environment: "{{ env }}"
  org:tech:contact: christian@casecommons.org
Stack.Policy:
  Statement:
  - Effect: "Deny"
    Action: "Update:*"
    Principal: "*"
    Resource: "*"

# Elasticsearch settings
Stack.Inputs.ElasticsearchKeyName: admin
Stack.Inputs.ElasticsearchInstanceType: m4.large
Stack.Inputs.ElasticsearchDesiredCount: '1'
Stack.Inputs.ElasticsearchImageId: ami-ceb3afb7
Stack.Inputs.ElasticsearchDockerImage: 610547539895.dkr.ecr.us-west-2.amazonaws.com/casecommons/elasticsearch
Stack.Inputs.ElasticsearchDockerImageTag: '2.4'
Stack.Inputs.ElasticsearchLoadBalancerPort: '9200'
Stack.Inputs.ElasticsearchPort: '9200'
Stack.Inputs.ElasticsearchHostname: elasticsearch-{{ env }}

# Log settings
Stack.Inputs.LogRetention: '30'
